name: Python CI on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change this to the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Download NLTK data
      run: |
        python -m nltk.downloader punkt
        python -m nltk.downloader stopwords
        python -m nltk.downloader wordnet
        python -m nltk.downloader omw-1.4
        python -m nltk.downloader punkt_tab

    - name: Run tests
      run: |
        python script.py
